# Generated by Django 4.2.7 on 2023-11-15 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_local_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=30)),
                ('descripcionProducto', models.CharField(max_length=30)),
                ('imagenProducto', models.ImageField(default='null', upload_to='')),
                ('categoria', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
